"use strict";

const RestaurantConstants = {
	RECEIVE_RESTAURANT: "RECEIVE_RESTAURANT",
	RECEIVE_RESTAURANTS: "RECEIVE_RESTAURANTS",
	UPDATE_REVIEW: "UPDATE_REVIEW",
	UPDATE_REVIEWS: "UPDATE_REVIEWS",
	REMOVE_REVIEW: "REMOVE_REVIEW"
};

module.exports = RestaurantConstants;
