# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 624732baf62df23c9b17de80d8392d10d715c6434dccfed9f696c5d2c973d6d7e6ffd496b28c9aa3ad2a855dbc01f5781e959de79049af5bec4a96cc34efe7f5

test:
  secret_key_base: db0c20c3116334bc33d5bbcd5cba8aea974542ce6baaa1b6283bf49c216731714c3b804909e192c7a55a6900112ccecfb3a2bb762792e230df048483fff9b4af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
